### ISSUE TITLE
Graph not loaded on first load of admin dashboard page

### ISSUE THREAD

**Issue by snufpunk** [onilab/magento-1-google-api-chart-fix#2]
On first load of admin dashboard page graph is not loaded (no error is displayed).

If the page is refreshed or an option selected from "select range" drop down menu - the graph shows up as expected.

When navigating to a different page in the backend and then back to dashboard page, graph is not shown again until page refresh / "select range" drop down menu.

Observed on CE 1.7.0.2 & 1.8.1.0

**Comment by artzwinger** [comment]
Hi there. Thank you, we appreciate your time and have fixed it for you. Please feel free to leave there the feedback about 0.0.2 version.

**Comment by snufpunk** [comment]
Works as expected now - thanks for the quick fix.

Link to GitHub is a good addition 👍
